# Generated by Django 4.2.1 on 2023-06-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_privacy_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('public', 'public'), ('friends', 'friends'), ('only me', 'only me')], default='public', max_length=10),
        ),
    ]
