# Generated by Django 4.2.1 on 2023-07-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicGroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('room_picture', models.ImageField(blank=True, null=True, upload_to='group_pictures/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='chat.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
