# Generated by Django 4.2.1 on 2023-07-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_publicgroupinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachment',
            name='file_name',
        ),
    ]
