# Generated by Django 4.2.1 on 2023-07-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_messageattachment_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachment',
            name='file_name',
        ),
    ]
