# Generated by Django 4.2.1 on 2023-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending')], max_length=20),
        ),
    ]
