# Generated by Django 4.2.1 on 2023-05-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, height_field=500, null=True, upload_to='profile_picture', width_field=500),
        ),
    ]
