# Generated by Django 4.2.1 on 2023-06-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0004_user_last_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
