# Generated by Django 4.2.1 on 2023-06-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
