# Generated by Django 4.2.1 on 2023-07-12 18:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0008_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
